### ISSUE TITLE
Microsoft GIF Animator

### ISSUE THREAD

**Issue by trenzterra** [fabianoriccardi/killed-by-microsoft#30]
**What's the Product's Name?** 
Microsoft GIF Animator

**Describe the product in a single sentence.**
Free software available to animate GIFs.

**When was the product launched? Provide a specific date, if possible.**

1996

**When was the product discontinued? Provide a specific date, if possible.**

Unknown - but I used it as a kid back in 2002 and even then it was no longer updated.

**What type of product was it? App, Service, or Hardware?**

App

Link to wiki: https://en.m.wikipedia.org/wiki/Microsoft_GIF_Animator

**Comment by fabianoriccardi** [comment]
Thanks for the contribution! added https://github.com/fabianoriccardi/killed-by-microsoft/commit/b24a012096cbf85c53b69abf77f71bfad974e719

As end date I consider the 1997, since it seems it never received an update. However, since it is a standalone local app, it virtually never dies. I have heard of people that can still use it under Win10...
