### ISSUE TITLE
ActiveVRML

### ISSUE THREAD

**Issue by Sgeo** [fabianoriccardi/killed-by-microsoft#55]
**What's the Product's Name?**

ActiveVRML

**Describe the product in a single sentence.**

ActiveVRML was a proposal by Microsoft for what VRML 2.0 should become. It was disregarded in favor of a different proposal, but was still maintained for a while afterwards.

**When was the product launched? Provide a specific date, if possible.**

1995?

**When was the product discontinued? Provide a specific date, if possible.**

I'm not sure, but not before 1996 as far as I can tell.

**What type of product was it? App, Service, or Hardware?**

Specification for 3D interactive worlds.

**Comment by fabianoriccardi** [comment]
Can you provide an link to a reference page? I had seen papers and some minor websites about this proposal, but a wiki page doesn't exist. Did someone implemented this specification?

**Comment by Sgeo** [comment]
https://archive.org/details/3dgraphicsvrml200000lema

Chapter 11, beginning on page 162
Appendix D, beginning on page 414

CD files at https://archive.org/details/laura-lemay-VRML

**Comment by fabianoriccardi** [comment]
I give a look to the links... I think it shouldn't be included since I would add only released "product", and ActiveVRML seems only a proposal for an eventual implementation (that is the "product"). For the same reason, I will avoid adding Windows 10X since it wasn't released, even if publicly Microsoft has released a good amount of information about it.

Hence, if case you agree, I would close the issue, otherwise let me know.
