### ISSUE TITLE
DotNetty

### ISSUE THREAD

**Issue by to11mtm** [fabianoriccardi/killed-by-microsoft#92]
**What's the Product's Name?**
DotNetty

**Describe the product in a single sentence.**
"DotNetty is a port of Netty, asynchronous event-driven network application framework for rapid development of maintainable high performance protocol servers & clients."

**When was the product launched? Provide a specific date, if possible.**
~September 2015 (Earliest Nuget Publish date I could find)

**When was the product discontinued? Provide a specific date, if possible.**
A github issue was filed on August 14th, 2020 asking whether the project is dead without a confirmed response as of the date of this obituary report (Oct 20, 2023): https://github.com/Azure/DotNetty/issues/542

**What type of product was it? App, Service, OS, or Hardware?**
App I guess?

**Comment by fabianoriccardi** [comment]
I would not insert this framework because it seems too "small". In particular: 

- It wasn't directed to end user 
- it doesn't have a website
- there isn't a page on wikipedia
- there is not any reference on Microsoft press release channels (blog, news ,.. ).

The most I found is https://devblogs.microsoft.com/dotnet/on-net-2122016-aaron-stannard/ ...

However, thanks for the contribution.
